# Generated by Django 4.2 on 2023-05-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_num', models.PositiveIntegerField(unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True)),
                ('shape', models.CharField(max_length=100)),
                ('color_front', models.CharField(max_length=30)),
                ('color_back', models.CharField(max_length=30)),
                ('bit', models.CharField(max_length=100)),
                ('prescription', models.CharField(max_length=30)),
                ('sungbun', models.TextField(blank=True, null=True)),
                ('efcy_qesitm', models.TextField()),
                ('use_method_qesitm', models.TextField()),
                ('atpn_warn_qesitm', models.TextField()),
                ('atpn_qesitm', models.TextField()),
                ('intrc_qesitm', models.TextField()),
                ('se_qesitm', models.TextField()),
                ('deposit_method_qesitm', models.TextField()),
            ],
        ),
    ]
